spring:
  application:
    name: application-mba
    datasource:
      druid:
        url: jdbc:mysql://rm-bp131820s97mp89aooo.mysql.rds.aliyuncs.com:3306/wowoshenghuo_mba?useUnicode=true&characterEncoding=utf8&useSSL=true
        username: wowoshenghuo_mba
        password: wowoshenghuo_mba
        max-wait: 30000
        initial-size: 50
        min-idle: 50
        max-active: 50
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  order:
    datasource:
      druid:
        url: jdbc:mysql://rm-bp131820s97mp89aooo.mysql.rds.aliyuncs.com:3306/wowoshenghuo_order?useUnicode=true&characterEncoding=utf8&useSSL=true
        username: wowoshenghuo_order
        password: wowoshenghuo_order
        max-wait: 30000
        initial-size: 50
        min-idle: 50
        max-active: 50
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7177


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:3333/eureka/

logging:
  level:
    com.example: debug
