spring:
  application:
    name: application-order
    datasource:
      druid:
        url: 
        username: 
        password: 
        max-wait: 30000
        initial-size: 50
        min-idle: 50
        max-active: 50
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
  order:
    datasource:
      druid:
        url: 
        username: 
        password: 
        max-wait: 30000
        initial-size: 50
        min-idle: 50
        max-active: 50
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7178


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:3333/eureka/

logging:
  level:
    com.example: debug
